// flow-typed signature: be87eba523767cf9bc40ca350379655d
// flow-typed version: <<STUB>>/p-throttle_v^1.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-throttle/index' {
  declare module.exports: $Exports<'p-throttle'>;
}
declare module 'p-throttle/index.js' {
  declare module.exports: $Exports<'p-throttle'>;
}
