// flow-typed signature: a92a43a3e64227e1f28829a4f6939203
// flow-typed version: <<STUB>>/p-timeout_v^2.0.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-timeout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-timeout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-timeout/index' {
  declare module.exports: $Exports<'p-timeout'>;
}
declare module 'p-timeout/index.js' {
  declare module.exports: $Exports<'p-timeout'>;
}
