// flow-typed signature: ec2673bc27aa8f7848c19e59137d4713
// flow-typed version: <<STUB>>/path-parser_v^4.0.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path-parser/dist/cjs/path-parser' {
  declare module.exports: any;
}

declare module 'path-parser/dist/es/path-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path-parser/dist/cjs/path-parser.js' {
  declare module.exports: $Exports<'path-parser/dist/cjs/path-parser'>;
}
declare module 'path-parser/dist/es/path-parser.js' {
  declare module.exports: $Exports<'path-parser/dist/es/path-parser'>;
}
